insert into public.diary_entries (
  entry_date,
  title,
  content,
  excerpt,
  image_url,
  image_alt,
  is_published
)
values
  ('2026-02-10', '[DUMMY] Quiet launch day',
   'Shipped the first public diary timeline. It felt incomplete at first, but once the scroll flow worked I realized the tone mattered more than polish. Writing this down so I remember that momentum beats overthinking.',
   'Shipped the first public diary timeline and learned momentum matters.',
   null,
   null,
   true),
  ('2026-02-04', '[DUMMY] Coffee + architecture notes',
   'Spent two hours untangling route strategy. Keeping /diary canonical and preserving /yearly-notes as compatibility redirect is small, but it keeps old links alive and future decisions cleaner.',
   'Settled the route architecture with /diary canonical and compatibility redirect.',
   null,
   null,
   true),
  ('2026-01-29', '[DUMMY] Evening reflection',
   'I expected the timeline to be decorative. It turned out to be emotional instead. Dates, small images, and short fragments made it feel like memory rather than content.',
   'Timeline design felt like memory, not just content.',
   'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=400&q=60',
   'Notebook and coffee on a wooden desk',
   true),
  ('2026-01-18', '[DUMMY] Debugging day',
   'Infinite scroll duplicated two entries after a refactor. Added deterministic ordering and an id-based dedupe guard. Tiny bug, big trust issue avoided.',
   'Fixed duplicate entries by adding deterministic ordering and id dedupe.',
   null,
   null,
   true),
  ('2025-12-28', '[DUMMY] Year-end audit',
   'Reviewing old projects showed how quickly assumptions age. I now keep a short paragraph after each milestone to capture why a choice was made.',
   'Added a habit of documenting rationale after each milestone.',
   null,
   null,
   true),
  ('2025-12-15', '[DUMMY] Small win',
   'Improved card readability by reducing visual noise. Less chrome, stronger text hierarchy, and tighter spacing made the diary feel calmer.',
   'Reduced visual noise to improve readability.',
   null,
   null,
   true),
  ('2025-11-30', '[DUMMY] Late-night build',
   'Worked until midnight restructuring admin form fields. Removing feature flags from the model made the experience more honest. A diary should be simple.',
   'Simplified admin form by removing unnecessary feature flags.',
   'https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=400&q=60',
   'Laptop with code editor open at night',
   true),
  ('2025-11-11', '[DUMMY] Writing practice',
   'I wrote three drafts of one entry and kept the shortest version. Clarity came from deleting, not adding.',
   'Shorter writing delivered better clarity.',
   null,
   null,
   true),
  ('2025-10-22', '[DUMMY] Team feedback',
   'Shared the timeline prototype with friends. Most feedback had nothing to do with code; people cared about how honest the writing felt.',
   'Feedback emphasized authenticity over technical detail.',
   null,
   null,
   true),
  ('2025-10-01', '[DUMMY] Travel note',
   'Wrote from an airport lounge. Delays are annoying, but waiting made me observe details I usually miss. Diary entry quality improved when I slowed down.',
   'Airport delay unexpectedly improved my writing quality.',
   'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=400&q=60',
   'Airplane wing seen through a window',
   true),
  ('2025-09-19', '[DUMMY] Refactor checkpoint',
   'Moved repeated formatting logic into utility helpers. The code shrank; confidence grew.',
   'Shared utilities reduced duplication and increased confidence.',
   null,
   null,
   true),
  ('2025-09-02', '[DUMMY] Reading notes',
   'Learned that data-heavy pages still need emotional pacing. Metrics explain behavior, but narrative keeps people scrolling.',
   'Narrative pacing matters even on data-heavy pages.',
   null,
   null,
   true),
  ('2025-08-21', '[DUMMY] Personal benchmark',
   'Set a rule: every entry must teach future-me one thing. If it does not, rewrite it.',
   'New rule: each entry must teach future-me one thing.',
   null,
   null,
   true),
  ('2025-08-07', '[DUMMY] Image experiment',
   'Tested mini thumbnails beside cards. Keeping them optional preserved flow while adding memory anchors where useful.',
   'Optional mini thumbnails improved memory anchors.',
   'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=60',
   'Open book with handwriting notes',
   true),
  ('2025-07-18', '[DUMMY] Mid-month recap',
   'The more I write publicly, the less I try to sound perfect. That paradox seems healthy.',
   'Public writing reduced perfection pressure.',
   null,
   null,
   true),
  ('2025-07-01', '[DUMMY] New month reset',
   'Started the month by deleting stale todos. Replacing them with fewer clear priorities made daily entries easier.',
   'Fewer clear priorities made daily notes easier.',
   null,
   null,
   true),
  ('2025-06-14', '[DUMMY] Learning sprint',
   'Spent a week revisiting fundamentals I thought I had mastered. Depth was worth the ego hit.',
   'Revisiting fundamentals created better depth.',
   null,
   null,
   true),
  ('2025-05-26', '[DUMMY] Sunday maintenance',
   'Ran cleanup scripts, fixed naming inconsistencies, and documented edge cases. Not glamorous, very effective.',
   'Cleanup and documentation paid off more than expected.',
   null,
   null,
   true),
  ('2025-04-09', '[DUMMY] Spring note',
   'I now track decisions and emotions in the same entry. Technical outcomes make more sense with context.',
   'Combining technical outcomes with emotional context improved insight.',
   null,
   null,
   true),
  ('2025-03-03', '[DUMMY] First timeline concept',
   'Sketched the very first timeline concept on paper. The current version is cleaner, but the core idea stayed the same: one continuous story.',
   'The first paper sketch established the continuous story concept.',
   null,
   null,
   true);
